# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  url = "project/"
  weight = 20

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 30

[[main]]
  name = "Courses"
  url = "course/"
  weight = 32

[[main]]
  name = "Softwares"
  url = "software/"
  weight = 35

[[main]]
  name = "Talks"
  url = "talk/"
  weight = 40

[[main]]
  name = "Blogs"
  url = "blog/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main_right]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/prashjha/"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/prashant_jha16"
  weight = 30
