# ----------------------------------
# Copyright (c) 2021 Prashant K. Jha
# ----------------------------------
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.145.0

    steps:
      - run:
          name: "Setup"
          command: |
            echo "#-----------------------------#"
            echo "Install key libraries"
            echo "#-----------------------------#"
            sudo apt-get install -y ca-certificates
            sudo apt-get install -y git
            echo "#-----------------------------#"
            echo "Hugo version"
            echo "#-----------------------------#"
            hugo version
            echo "#-----------------------------#"
            echo "Git config"
            echo "#-----------------------------#"
            git config --global user.email "pjha.sci@gmail.com"
            git config --global user.name "Prashant K. Jha"
            git config --global user.name "prashjha"
      - run:
          name: "Build website and push"
          command: |
            echo "#-----------------------------#"
            echo "Clone repo"
            echo "#-----------------------------#"
            git clone https://github.com/prashjha/my-website.git
            cd my-website
            echo "#-----------------------------#"
            echo "Clone github pages repo in a public folder"
            echo "#-----------------------------#"
            git clone https://github.com/prashjha/prashjha.github.io.git public
            echo "#-----------------------------#"
            echo "Clean public folder"
            echo "#-----------------------------#"
            cd public
            git rm -r .
            git commit -m "cleaning"
            echo "#-----------------------------#"
            echo "Run hugo"
            echo "#-----------------------------#"
            cd ..
            HUGO_ENV="production"  hugo -F
            echo "#-----------------------------#"
            echo "Commit new files into github pages repo"
            echo "#-----------------------------#"
            cd public
            git add .
            git commit --allow-empty -m "update" 
            echo "#-----------------------------#"
            echo "Push updates to github pages repo"
            echo "#-----------------------------#"
            git push -q https://${G_TOKEN}@github.com/prashjha/prashjha.github.io.git main
      - run:
          name: "Update content folder of lab website repo"
          command: |
            echo "#-----------------------------#"
            echo "Clone ceadpx-website repo"
            echo "#-----------------------------#"
            git clone https://github.com/CEADpx/ceadpx-website.git
            cd ceadpx-website
            echo "#-----------------------------#"
            echo "Copy files from my-website to ceadpx-website"
            echo "#-----------------------------#"
            declare -a fldrs=("event" "post" "project" "publication" "software" "teaching")
            for s in ${fldrs[@]}; do
                # clean and copy
                echo "Removing ${s} folder"
                rm -r content/${s}
                echo "Copying ${s} folder from my-website"
                cp -r ../my-website/content/${s} content/${s}
            done
            # copy CV
            echo "Copying cv.pdf from my-website"
            cp -av ../my-website/static/uploads/cv.pdf static/uploads/
            echo "#-----------------------------#"
            echo "Commit updates"
            echo "#-----------------------------#"
            git add .
            git commit --allow-empty -m "update" 
            echo "#-----------------------------#"
            echo "Push updates to github pages repo"
            echo "#-----------------------------#"
            git push -q https://${G_TOKEN}@github.com/CEADpx/ceadpx-website.git main